# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(default='test text', max_length=200),
            preserve_default=False,
        ),
    ]
